[package]
name = "scrapt"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "manifest_common",
    "manifest_scratch",
    "manifest_scrapt",

    "lang",
]

[dependencies]
manifest_scratch = { path = "manifest_scratch" }
manifest_scrapt = { path = "manifest_scrapt" }
lang = { path = "lang" }
