[package]
name = "scrapt"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "manifest/common",
    "manifest/scratch",
    "manifest/scrapt",

    "lang",
]

[dependencies]
manifest_scratch = { path = "manifest/scratch" }
manifest_scrapt = { path = "manifest/scrapt" }
lang = { path = "lang" }
