[package]
name = "unscratch"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "manifest_common",
    "manifest_scratch",
    "manifest_unscratch",

    "unscript",
]

[dependencies]
manifest_scratch = { path = "manifest_scratch" }
manifest_unscratch = { path = "manifest_unscratch" }
unscript = { path = "unscript" }
