[package]
name = "scrapt"
version = "0.1.0"
authors = ["rabuu <dev@rbuurman.de>"]
edition = "2021"
description = "Script your Scratch!"

[workspace]
members = [
    "manifest/common",
    "manifest/scratch",
    "manifest/scrapt",

    "lang",
]

[workspace.dependencies]
manifest_common = { path = "manifest/common" }
manifest_scratch = { path = "manifest/scratch" }
manifest_scrapt = { path = "manifest/scrapt" }
lang = { path = "lang" }

serde = { version = "1", features = ["derive"] }

[dependencies]
manifest_scrapt = { workspace = true }
manifest_scratch = { workspace = true }
lang = { workspace = true }
clap = { version = "4", features = ["derive"] }
