[package]
name = "scrapt"
version = "0.1.0"
authors = ["rabuu <dev@rbuurman.de>"]
edition = "2021"
description = "Script your Scratch!"

[workspace]
members = [
    "manifest/common",
    "manifest/scratch",
    "manifest/scrapt",
    "lang",
]

[workspace.dependencies]
manifest_common = { path = "manifest/common" }
manifest_scratch = { path = "manifest/scratch" }
manifest_scrapt = { path = "manifest/scrapt" }
lang = { path = "lang" }

serde = { version = "1", features = ["derive"] }
itertools = "0.12"
thiserror = "1"
tracing = "0.1"

[dependencies]
manifest_scrapt = { workspace = true }
manifest_scratch = { workspace = true }
lang = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

# binary only
clap = { version = "4", features = ["derive"] }
anyhow = "1"
tracing-subscriber = "0.3"
zip = { version = "0.6", default-features = false }
md-5 = "0.10"
