PROG = HEAD*

HEAD = GLOBAL_HEAD | VARS_HEAD | LISTS_HEAD | BROADCASTS_HEAD | COSTUMES_HEAD | SOUNDS_HEAD

GLOBAL_HEAD = "global", "{", GLOBAL_DECL+, "}"
GLOBAL_DECL = GLOBAL_KEYWORD, "=", value, ";"
GLOBAL_KEYWORD = "tempo" | "volume" | "videoTransparency" | "videoState"

VARS_HEAD = "vars", "{", VAR_DECL+, "}"
VAR_DECL = name, ("=", value)?, ";"

LISTS_HEAD = "lists", "{", LIST_DECL+, "}"
LIST_DECL = name, ("=", "[", (value, ",")*, value, ","?, "]")?, ";"

BROADCASTS_HEAD = "{", BROADCASTS_DECL+, "}"
BROADCASTS_DECL = name, ";"

COSTUMES_HEAD = "{", COSTUMES_DECL+, "}"
COSTUMES_DECL = "*"?, name, ":", COSTUMES_TYPE, ("=", path)?, ";"
COSTUMES_TYPE = "SVG" | "PNG"

SOUNDS_HEAD = "{", SOUNDS_DECL+, "}"
SOUNDS_DECL = "*"?, name, ":", SOUNDS_TYPE, ("=", path)?, ";"
SOUNDS_TYPE = "WAV" | "MP4"
